name: cryptotracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^7.1.0
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.3
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
